version: "2"
sql:
  - engine: "postgresql"
    queries: 
    - "machine_query.sql"
    - "user_query.sql"
    - "shift_query.sql"
    - "task_query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "postgres"
        out: "../../internal/database/postgres"
        sql_package: "pgx/v5"