basePath: /api
consumes:
- application/json
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  handler_output.ShiftOutput:
    properties:
      createdat:
        type: string
      deactivatedat:
        type: string
      id:
        type: integer
      isactive:
        type: boolean
      machineid:
        type: integer
      shiftMaster:
        type: integer
    type: object
  handler_output.UserOutput:
    properties:
      bitrixid:
        type: integer
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
  postgres.ShiftTask:
    properties:
      shiftid:
        type: integer
      taskid:
        type: integer
    type: object
  postgres.ShiftWorker:
    properties:
      shiftid:
        type: integer
      userid:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: example@example.com
    name: API Support
    url: http://81.177.220.96/
  description: API for managing shifts and adding tasks
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Shift manager api
  version: "1.0"
paths:
  /api/machine/{id}:
    put:
      consumes:
      - application/json
      description: change machine status to need repair machine:id from the database.
      parameters:
      - description: Machine id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No connection
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: invalid data
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: missing id
          schema:
            $ref: '#/definitions/gin.H'
      summary: change machine status to need repair
      tags:
      - machine
  /api/shifts:
    get:
      description: get out shifts that are active.
      produces:
      - application/json
      responses:
        "200":
          description: List of active shifts
          schema:
            items:
              $ref: '#/definitions/handler_output.ShiftOutput'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/gin.H'
      summary: get out shifts that are active
      tags:
      - shifts
  /api/users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/handler_output.UserOutput'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get list of users
  /api/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user:id from the database.
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No connection
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: invalid data
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: missing id
          schema:
            $ref: '#/definitions/gin.H'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Return list of shift workers  by shift id.
      parameters:
      - description: Shift id
        format: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of shift workers by shift id
          schema:
            items:
              $ref: '#/definitions/postgres.ShiftWorker'
            type: array
        "400":
          description: invalid data
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get list of shift workers  by shift id
      tags:
      - shift worker
  /api/users/{role}:
    get:
      consumes:
      - application/json
      description: Return list of users with role.
      parameters:
      - description: Users role
        format: id
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of users with role
          schema:
            items:
              $ref: '#/definitions/handler_output.UserOutput'
            type: array
        "400":
          description: invalid data
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get list of users with role
      tags:
      - students
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
